RawDataRecord with unit tests
mdabrowski1990/uds pull request #297
Opened 2024-11-10 16:33 UTC by n135c10r

# Description
Draft of Implementation for RawDataRecord with unit tests.
Refactoring the Data Records directory structure.

# How Has This Been Tested?
Executing unit tests.

# Process

I know the [process](https://github.com/mdabrowski1990/uds/wiki/Software-Development-Life-Cycle) and did my best to follow it

2024-11-11 16:04 UTC, mdabrowski1990 commented on tests/software_tests/database/data_record/test_abstract_data_record.py
> +from uds.database.data_record import AbstractDataRecord
Let's import directly from the module `uds.database.data_record.abstract_data_record`

2024-11-11 16:06 UTC, mdabrowski1990 commented on uds/database/__init__.py
> +from .data_record import RawDataRecord
we need to provide `AbstractDataRecord` and `DecodedDataRecord` as well

2024-11-11 16:13 UTC, mdabrowski1990 commented on uds/database/data_record/abstract_data_record.py
After thinking it through, I am pretty sure we do not need `DataRecordType` class at all (we might use classes). You might remove it or keep it as it is and I would remove it at the first occasion.

2024-11-11 16:14 UTC, mdabrowski1990 commented on uds/database/data_record/raw_data_record.py
We need module docstring.

2024-11-11 16:19 UTC, mdabrowski1990 commented on uds/database/data_record/raw_data_record.py
> +        if not isinstance(length, int) or length <= 0:
I would do: `self.length = length`  here. Instead provide setter for `length` property. There you can handle type and value errors. Then you would handle all improper types and values assignment, not just on object creation.

You can base on https://github.com/mdabrowski1990/uds/blob/main/uds/transport_interface/can/common.py (e.g. `n_as_timeout` property)

2024-11-11 16:21 UTC, mdabrowski1990 commented on uds/database/data_record/raw_data_record.py
> +        return DecodedDataRecord(name=self.name, raw_value=raw_value, physical_value="Raw Data Record")
It should be `DecodedDataRecord(name=self.name, raw_value=raw_value, physical_value=raw_value)` (this is an edge case, cause Raw Data Record do not have mapping, so physical and raw value are the same.

2024-11-11 16:28 UTC, mdabrowski1990 commented on tests/software_tests/database/data_record/test_raw_data_record.py
I would appreciate, if you could extend these tests (I know that I make very comprehensive and deep testing, so just let me know if you think this is too much for you and I will finish this).

I would like to cover with tests:
- multiple cases to make sure that `__init__`, `decode` and `encode` methods do not malfunction with various parameters
- we do 100% branch and decisions coverage (so every error and code path has to be covered)

You can base on: https://github.com/mdabrowski1990/uds/blob/main/tests/software_tests/transport_interface/can/test_common.py

2024-11-11 16:30 UTC, mdabrowski1990 requested changes
I like that you separated `data_record` module.
I have left plenty of comments, but I think this is a really good start.

2024-11-11 21:16 UTC, n135c10r commented on tests/software_tests/database/data_record/test_raw_data_record.py
Ok, no problem. I will do it tomorrow. Please check if rest of the fixes are acceptable :)

2024-11-18 12:20 UTC, mdabrowski1990 commented on uds/database/data_record/__init__.py
> +__all__ = ["AbstractDataRecord", "DecodedDataRecord", "RawDataRecord"]
please remove `__all__` (everything we import is supposed to be available for the user)

2024-11-18 12:20 UTC, mdabrowski1990 commented on tests/software_tests/database/data_record/test_abstract_data_record.py
> +    def test_data_record_type(self):
let's remove this

2024-11-18 12:35 UTC, mdabrowski1990 commented on uds/database/data_record/raw_data_record.py
> +        return DecodedDataRecord(name=self.name, raw_value=raw_value, physical_value=raw_value)
let's protect from:
- user providing value of other than int type -> Type Error
- user providing value out of range -> Value Error

tip: To make check whether value is in range, you might want to add property `max_raw_value` (equals `(1<<length)-1`)

2024-11-18 12:35 UTC, mdabrowski1990 commented on uds/database/data_record/raw_data_record.py
> +        return physical_value  # type: ignore
lets protect from wrong type and value out of range provided by the user

2024-11-26 06:38 UTC, mdabrowski1990 commented on uds/database/data_record/raw_data_record.py
> +    def max_raw_value(self):
let's move it to `AbstractDataRecord` (it is common for all DataRecords)

2024-11-26 06:42 UTC, mdabrowski1990 commented on tests/software_tests/database/data_record/test_raw_data_record.py
> +        with pytest.raises(TypeError):
we need one more before:
`mock_isinstance.return_value = False` to make sure that type check failed

2024-11-26 06:43 UTC, mdabrowski1990 commented on tests/software_tests/database/data_record/test_raw_data_record.py
> +        with pytest.raises(TypeError):
we need one more line before with pytest.raises:
mock_isinstance.return_value = False to make sure that type check failed

2024-11-26 06:56 UTC, mdabrowski1990 reviewed
almost ready to be merged
please check why codecov reports missing coverage (there is something wrong with TypeError tests, probably it would be solved after my comments are applied)

2024-11-28 06:40 UTC, mdabrowski1990 approved these changes

2024-11-28 07:27 UTC, merged